### ISSUE TITLE
Host Content in css with sass ampersand produces wrong output

### ISSUE THREAD

**Issue by gjuchault** [angular/angular#10445]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The CSS generated is wrong. There is a space that should not be here, which breaks everything.

**Expected/desired behavior**

Correct CSS

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Inside a component, I put this SASS:

```sass
:host::content {
  &:last-of-type > .list__item {
    border-bottom: 0;
  }
}
```

**What is the expected behavior?**

Generated CSS should be:

```css
[_nghost-wyo-15]:last-of-type > .be-list__item {
  border-bottom: 0; }
```

Instead I have:

```css
[_nghost-wyo-15] :last-of-type > .be-list__item {
  border-bottom: 0; }
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** SASS

**Comment by gjuchault** [comment]
Additional note:

```scss
:host::content:last-of-type > .#{$pre}-list__item {
  border-bottom: 0;
}
```

This outputs the same
