### ISSUE TITLE
Wrong generated css encapsulation attributes when using nested selectors without :host

### ISSUE THREAD

**Issue by thomaspink** [angular/angular#11534]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When using the default emulated view encapsulation, angular appends the wrong attributes to selectors without :host context.

Template (`my-comp.component.html`):
```html
<my-comp aria-hidden="true">
  <div class="container"></div>
</my-comp>
```

SCSS (`my-comp.component.scss`):
```scss
:host {
  display: block
}
.container {
  display: block;
  [aria-hidden="true"] & {
    display: none;
  }
}
```

Generated CSS
```css
[_nghost-kwp-3] { display: block; }
.container[_ngcontent-kwp-3] { display: block; }

/* Wrong _ngcontent-kwp-3 attribute selector */
[aria-hidden="false"][_ngcontent-kwp-3] .container[_ngcontent-kwp-3] { display: none; }
```

**Expected behavior**
```css
[_nghost-kwp-3] { display: block; }
.container[_ngcontent-kwp-3] { display: block; }

/* The appended attribute selector should be _nghost-kwp-3 */
[aria-hidden="false"][_nghost-kwp-3] .container[_ngcontent-kwp-3] { display: none; }
```

**Additional information**
If you add the :host selector it works fine. But in my opinion, the above problem should work, because it is a valid and working scss and a common pattern.

Working SCSS (`my-comp.component.scss`):
```scss
:host {
  display: block
}
.container {
  display: block;

  /* added :host */
  :host[aria-hidden="true"] & {
    display: none;
  }
}
```

Generated CSS
```css
[_nghost-kwp-3] { display: block; }
.container[_ngcontent-kwp-3] { display: block; }

/* Works fine now */
[_nghost-kwp-3][aria-hidden="false"] .container { display: none; }
```

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.6
* **Browser:** [all] 
* **Language:** [SCSS]
