### ISSUE TITLE
Support @page css rule into component styles

### ISSUE THREAD

**Issue by ocombe** [angular/angular#11860]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior** 
When I use the [`@page`](https://developer.mozilla.org/en/docs/Web/CSS/@page) css rule in my component style, it gets encapsulated but it shouldn't.

For example the following css:
```css
@page {
    size: 1500px 2048px;
}
```

is transformed into 
```css
@page[_ngcontent-tue-10] {
  size: 1500px 2048px;
}
```

It works fine with `@media` rules:
```css
@media print {
    :host {
        margin: 0 auto;
        padding: 0 1rem;
    }
}
```

is transformed into:
```css
@media print {
  [_nghost-tue-10] {
    margin: 0 auto;
    padding: 0 1rem;
  }
}
```

which works just as expected.

**Expected behavior**
The `@page` css rule should have the same behavior as `@media` and shouldn't be encapsulated.

**What is the motivation / use case for changing the behavior?**
The `@page` css rule doesn't work in component styles right now

**Please tell us about your environment:**
* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** all
