### ISSUE TITLE
Anular2 styling ng-cotent from :host

### ISSUE THREAD

**Issue by maxshutyak** [angular/angular#11966]
In 2.0.0.rc4 angular i have
```html
<profile-actions class="profile-actions" _nghost-erf-13="">
    <div class="profile-actions-box" _ngcontent-erf-13></div>
    <div class="profile-actions-box" _ngcontent-erf-13></div>
 </profile-actions>
```
Now in stable 2.0.0 i have
```html
<profile-actions class="profile-actions" _nghost-erf-13="">
    <div class="profile-actions-box"></div>
    <div class="profile-actions-box"></div>
 </profile-actions>
```
 Now i cant use styles like this. In rc4 this styles works well:
```scss
:host(.profile-actions) {
  display: flex;
  .profile-actions-box {
        flex: 1 auto;
        text-align: left;
   }
}
```
