### ISSUE TITLE
Incorrect :host-context css in emulated mode

### ISSUE THREAD

**Issue by eugenyshchelkanov** [angular/angular#11972]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When `:host-context()` has a tag selector the style is not applied when selector matches. Class selector works fine.

Example of working style: `:host-context(.test)`

Example of not working style: `:host-context(div)`

**Expected behavior**
Both styles should work

**Reproduction of the problem**
[Plunk](http://plnkr.co/edit/Rj9dEMO2QVb04b5Zr2zx)

**What happens**
In the plunk above Angular generates the following CSS:
```css
[_nghost-dbj-2]div   div[_ngcontent-dbj-2], div   [_nghost-dbj-2]   div[_ngcontent-dbj-2] {
      background-color: green;
}
[_nghost-dbj-2].test   div[_ngcontent-dbj-2], .test   [_nghost-dbj-2]   div[_ngcontent-dbj-2] {
      background-color: red;
}
```
I assume that `[_nghost-dbj-2]div` is an invalid selector and browser discards the whole line so the style is never applied.

**Please tell us about your environment:**
* **Angular version:** 2.0.1
* **Browser:** Chrome, Firefox
* **Language:** all
