### ISSUE TITLE
Pub build Fails on Angular2 Transformers in Vanilla Project

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#1918]
pubspec.yaml
```
name: ng_2
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: any
  browser: any
  dartson: '>=0.2.2 <1.0.0'
transformers:
- dartson
- angular2:
    entry_points:
        - web/main.dart
    reflection_entry_points:
        - web/main.dart
- $dart2js:
    minify: false
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
```

Output:

```
Error in lib/src/transform/template_compiler/transformer.dart: Unexpected token '''

Stack Trace: #0      parseCompilationUnit (package:analyzer/analyzer.dart:70:52)
#1      createNgDeps (package:angular2/src/transform/directive_processor/rewriter.dart:24:3)
#2      DirectiveProcessor.apply.<apply_async_body> (package:angular2/src/transform/directive_processor/transformer.dart:36:23)
#3      _RootZone.runUnary (dart:async/zone.dart:1155)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#6      _Future._completeWithValue (dart:async/future_impl.dart:368)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

Full Output:
http://pastebin.com/Q2KrdcmC
