### ISSUE TITLE
CSS on recursive component results in `-shadowcsshost` pattern

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#19445]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I created a recursive component (See [plnkr](http://plnkr.co/edit/SN7ymjYwNdIgwfLakzCt?p=preview)):
```JavaScript
@Component({
  selector: 'ng-test',
  styleUrls: ['./src/component.css'],
  template: `
    <p>I am {{data.name}}</p>
    <ng-template [ngIf]="data.data">
      <ng-test [data]="data.data"></ng-test>
    </ng-template>`
})
```

with the following CSS:
```css
:host {
  color: red;
}
  
:host > :host {
  color: green;
}
```

The CSS on the page becomes the following:
```css
[_nghost-c0] {
  color: red;
}
  
[_nghost-c0]    > -shadowcsshost {
  color: green;
}
```

## Expected behavior
I expected `component1` to have the color red and `component2` to have the color green

## Minimal reproduction of the problem with instructions
[plnkr](http://plnkr.co/edit/SN7ymjYwNdIgwfLakzCt?p=preview)

## Environment

<pre><code>Angular version: 4.4.3</code></pre>
