### ISSUE TITLE
Form control's state is not correctly when ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by lonyel** [angular/angular#19759]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When the compoent's changeDetection: ChangeDetectionStrategy.OnPush, the form control(required,value is empty) state is ng-valid. After cklicked any,the state is ok.
But,when use formControlName,the state is ok.

## Expected behavior
The state=ng-invalid

## Minimal reproduction of the problem with instructions

app.component.ts:
```js
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  domain = { a: 100, b: '', c: new Date() };
  
  constructor() {
  }
}
```
app.compoent.html:
```html
<div>
  <form [formGroup]="form">
    <div class="form-group">
      <label>A</label>
      <input type="number" [(ngModel)]="domain.a" name="a">
    </div>
    <div class="form-group">
      <label>B</label>
      <input type="text"  [(ngModel)]="domain.b" name="b" required>
    </div>
    <div class="form-group">
      <label>C</label>
      <input type="date"  [(ngModel)]="domain.c" name="c">
    </div>
  </form>
</div>
```
app.component.scss:
```scss
form {
    .ng-valid[required],
    .ng-valid.required {
        border-left: 5px solid #42A948;
        /* green */
    }
    .ng-invalid:not(form):not(div) {
        border-left: 5px solid #a94442;
        /* red */
    }

}
```
## Environment
Angular version: 4.4.5

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6 
- Platform:  Windows

Others:

</code></pre>
