### ISSUE TITLE
bug(core/css-encapsulation): View Encapsulation overrules wildcard selectors

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#20559]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The wildcard selector `*` is being overruled by angular's default `Emulated` view encapsulation. The view encapsulation preprocessor converts
```scss
  router-outlet + * {
    grid-area: content;
    background: greenyellow;
  }
```
to the following css
```scss
  router-outlet[_ngcontent-c0] + *[_ngcontent-c0] {
    grid-area: content;
    background: greenyellow;
  }
```

## Expected behavior
The wildcard selector `*` should remain a wildcard selector without specialization.

## Minimal reproduction of the problem with instructions
A full example of the issue can be found in [this application](https://stackblitz.com/edit/angular-css-grid-holy-grail).

## What is the motivation / use case for changing the behavior?
See the thread on [StackOverflow](https://stackoverflow.com/questions/47356648/apply-css-to-routed-components) and https://github.com/angular/angular/issues/20558. A sibling wildcard would solve the router selection issue for a dynamically inserted component.

## Environment
<pre><code>Angular version: 5.0.2</code></pre>
