### ISSUE TITLE
Dart: static members of component not accessible in HTML templates

### ISSUE THREAD

**Issue by stevenroose** [angular/angular#22345]
## I'm submitting a...
  - [x] Feature request

## Current behavior
```dart
@Component(
  [...]
  template: '''<div *ngFor="let element of elementsToShow">{{element}}</div>'''
  directives: [CORE_DIRECTIVES],
)
class MyComponent {
  static final List<String> elementsToShow = ["one", "two", "three"];
}
```

Currently throws an error: 
```
EXCEPTION: NoSuchMethodError: method not found: 'get$elementsToShow' (_ctx.get$elementsToShow is not a function)
```

## Expected behavior
The static member `elementsToShow` is accessible just like a non-static class member.

## Minimal reproduction of the problem with instructions
See current behavior.

## What is the motivation / use case for changing the behavior?
Static members are intended for members that are the same for every instance of the class. Using Angular should not force the user to move those to a non-static member, or force the creation of a non-static getter to forward this variable.

## Environment
```yaml
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  http: ^0.11.3+16
  logging: ^0.11.3+1
  path: ^1.5.1
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_components: ^0.8.0
  stream_transform: ^0.0.6
  ng_bootstrap: any
  cookie: ^0.0.4
  intl: ^0.15.2
```

Angular version: 4.0.0+2 (Dart)

Browser:
- [X] Chrome (desktop) version 64.0.3282.85 (Official Build) beta (64-bit)
 
For Tooling issues:
- Platform: Arch Linux AMD64
