### ISSUE TITLE
Example project for Webpack config guide not working

### ISSUE THREAD

**Issue by SerhiDi** [angular/angular#22941]
1. Example project not working

 Example project for Webpack config guide not working.
[https://angular.io/guide/webpack](https://angular.io/guide/webpack) 
[webpack.zip](https://angular.io/generated/zips/webpack/webpack.zip) 
Always show `Loading...` app.component not loading

2. `background-image` trouble

I use only Webpack `config` folder in my Angular 5 project
But, `background-image` not working.

I have 404 error for the image file in the browser console.
`img.png` - in the same folder with `app-component` css/ts files, 

app.component.html
```javascript
<div class="bg"></div>
```
app.component.css
```css
.bg {
    background-image: url('./img.png'); // error in console
}
```

All working correctly if I use `img` tag:

app.component.html
```javascript
<img src="./img.png" alt="test img">
```

Or if I use a full path:

app.component.css
```css
.bg {
    background-image: url('src/app/img.png'); // working
}
```
But it is stupid, I want encapsulate image in component, for reuse it.
And this path not correct after build.
How can I use `background-image` as in regular CSS?
