### ISSUE TITLE
Remove Animations Metadata from Decorators and Place it in CSS

### ISSUE THREAD

**Issue by jfftck** [angular/angular#24327]
Move the animation metadata to CSS files and allow importing from common animation CSS, as the current animations in the decorator is very limited on reuse and makes the components very messy.

The current @angular/animations module requires about 3 MB and it is very static, the useAnimation metadata is very limited on how it can be used that it is a joke. But, since CSS is static, it would be the better candidate for hosting this information.

Then support for CSS variables and injecting data into these variables would remove the static nature and allow much cleaner code for components and the templates.

Added bonus is animations can be attached to the elements without an HTML attribute.

I think the biggest issue that I have with the current animations is that they are no better than code full of magic numbers/variables and that is seen as a bad practice. 

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

**Comment by jfftck** [comment]
Currently Angular does animations like this:

```javascript
...
animations: [trigger('buttonAni', [
  transition('* <=> *', [
    query(':leave', [
      style({transform: 'scaleX(1)', opacity: 1}),
      animate(
        '125ms cubic-bezier(0.4, 0.0, 0.2, 1)',
        style({transform: 'scaleX(0)', opacity: 0})
      )
    ], { optional: true }),
    query(':enter', [
      style({transform: 'scaleY(0)', opacity: 0}),
      animate(
        '500ms cubic-bezier(0.4, 0.0, 0.2, 1)',
        style({transform: 'scaleY(1)', opacity: 1})
      )
    ],
    { optional: true })
  ])
])]
...
```

```html
<div class="fake-button" [@buttonAni]>
```

But I feel that moving the metadata to CSS would clean up the code:
**button-animation.css**
```css
:root {
  --enter-timing: 500ms;
  --leave-timing: 125ms;
}

@-ng-animate(button) {
  @-ng-leave {
    @-ng-timing: var(--leave-timing);

    0% {
      transform: scaleX(1);
      opacity: 1;
    }

    100% {
      transform: scaleX(0);
      opacity: 0;
    }
  }

  @-ng-enter {
    @-ng-timing: var(--enter-timing);

    -ng-start {
      transform: scaleY(0);
      opacity: 0;
    }

    -ng-end {
      transform: scaleY(1);
      opacity: 1;
    }
  }
}
```
**fake-button.component.css**
```css
@-ng-import(button-animation.css) {
  --leave-timing: 250ms;
  --enter-timing: {{ enter-timing }};
}

.fake-button {
  -ng-animate: button;
}
```

That would allow attaching the animation to any part of a component and allow reusable animations.

Also, notice that there is custom property injection in the component CSS to the animation CSS and a component variable extraction.

_Note_
This syntax should have the following rules:
* Attaching would only be available for component CSS
* Attaching more than one animation should merge them with the priority of properties going from first to last to match standard CSS rules (box-shadow, text-shadow, background...)

This is just a simple example and does not cover all of the metadata properties that the current animation framework has, but they should follow the same kind of syntax.
