### ISSUE TITLE
@angular/animations fallback to css keyframes does not generate prefixed properties correctly

### ISSUE THREAD

**Issue by FreekMencke** [angular/angular#25282]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support reques
[ ] Other... Please describe:
</code></pre>

## Current behavior
When creating an Angular Animation with a webkit prefixed property, the property is incorrectly converted from camelCase to the correct property string. 

### Example
Angular animation:
```typescript           
style({
    'webkitClipPath': 'circle(150%)',
    'clipPath': 'circle(150%)'
}),
animate(`${circleTransitionDurationClosing}ms ${cubicBezierValue}`, style({
    'webkitClipPath': 'circle(0%)',
    'clipPath': 'circle(0%)'
}))
```

Generated output:
```css
<style>@keyframes gen_css_kf_0 {
 0% {
  clip-Path: circle(150%);
  webkit-Clip-Path: circle(150%);
  animation-timing-function: cubic-bezier(0.4, 0.0, 0.2, 1);
  }
 100% {
  clip-Path: circle(0%);
  webkit-Clip-Path: circle(0%);
  }
}
</style>
```

The `'webkitClipPath': 'circle(150%)'` is converted to `webkit-Clip-Path: circle(150%)` in the css keyframe animation.

## Expected behavior
`'webkitClipPath': 'circle(150%)'` should be converted to `-webkit-clip-path: circle(150%)`. Without the starting `-` the property will not work, because it does not exist.

## Minimal reproduction of the problem with instructions
You can find a simple reproduction of the problem here:
https://stackblitz.com/edit/angular-animations-prefix-bug

## What is the motivation / use case for changing the behavior?
It makes no sense that prefixed properties would not be supported in the css fallback.

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
Any browser without web-animations support (safari, safari iOS, Edge, ...)

</code></pre>

*Edited to add a reproduction in stackblitz.*
