### ISSUE TITLE
Host attributes: Be able to conditionally add or remove an attribute

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2869]
A common S/CSS technique when styling a component within a `:host` selector is using the existence of an attribute to drive style. For example, Polymer's [`<paper-button>`](https://elements.polymer-project.org/elements/paper-button) works something like this:

```scss
:host {
  &[disabled] {
    pointer-events: none;
  }
}
```

Unfortunately the only way to manipulate one own's attributes is a simple bindings:

```scss
:host {
  &[is-disabled="true"] {
    pointer-events: none;
  }
}
```

```dart
@Component(
  host: const {
    '[attr.is-disabled]': 'isDisabled'
  }
)
class FooComponent {
  bool _isDisabled = false;
  String get isDisabled => _isDisabled.toString();
}
```

Or, inject an `ElementRef` and access `nativeElement` :unamused: 

Both of these are OK workarounds, but also mean it's not trivial to use Polymer components that rely on the existence of an attribute (not a value).

Proposal
---

Have an alternative syntax for adding/removing attributes:

```html
<!-- 'attr-if' looks for a boolean instead of a String -->
<button [attr-if.disabled]="isDisabled"></button>
```
