### ISSUE TITLE
EmulatedScopedShadowDom: Not requiring ':host' to wrap everything in the stylesheet

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2872]
The way native shadow DOM works is that the entire stylesheet is encapsulated for the component.

CSS style:

```css
.my-private-thing {
  color: red;
}
```

HTML template:

```html
<div class="my-private-thing">Hello World</div>
```

However, it is required today to wrap everything in `:host`:

```css
:host .my-private-thing {
  color: red;
}
```

While this is an OK workaround, it's a lot of extra boilerplate.
