### ISSUE TITLE
Emulated Shadow DOM: Does not properly shim ::shadow and /deep/ selectors

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2932]
Reproduction case:

CSS
---

```css
.red-icon::shadow i { color: red; }
```

Expected
---

```css
.red-icon[_ngcontent-1] i[_ngcontent-2] { color: red; }
```

```html
<div class="red-icon" _ngcontent-1><i _ngcontent-2></i></div>
```

Actual
---

The 'i' element is not incremented, but it is in the HTML

```css
.red-icon[_ngcontent-1] i[_ngcontent-1] { color: red; }
```

```html
<div class="red-icon" _ngcontent-1><i _ngcontent-2></i></div>
```

The `&::shadow i`, rule is rewritten and essentially dropped: 

https://github.com/angular/angular/blob/6cdeab9279c956cc4d1f83194d0902f2bb09207f/modules/angular2/src/core/compiler/shadow_dom_emulation/shadow_css.js

**Comment by vicb** [comment]
`.red-icon[_ngcontent-1] i[_ngcontent-2] { color: red; }`

I don't think this would ever be possible - the content (`_ngcontent-2`) is dynamic and it would be impossible to pre-process the styles at compile time.

Would a `i { color: red; }` style in your `red-icon` component work ?

Notes:
- The CSS shim is a port from polymer,
- The shim is no meant to be exahaustive but to cover the vast majority of use cases,
- There are cases where the shim is known not to work - in such cases, you can then use `polyfill-...` rules, more info in [shadow_css.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/shadow_dom/shadow_css.ts)

@rkirov you mentionned an other bug in the shim, is there a GH issue ? please also make sure o check polymer: the bug might have been fixed there (or might need to be fixed - not sure if the shim is still used post 0.8)

**Comment by rkirov** [comment]
The other issue is - https://github.com/angular/angular/issues/2782

**Comment by matanlurey** [comment]
This is actually a SASS mixin that can be applied in any component, something like

```scss
@mixin icon-size($px) {
  &::shadow i {
    font-size: $px;
  }
}
```
