### ISSUE TITLE
::ng-deep leaks out of component

### ISSUE THREAD

**Issue by mmalerba** [angular/angular#29965]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
Not sure

### Description
Using ::ng-deep` causes the styles to be applied to elements completely outside of the component's template. According to the documentation it should only affect elements inside the child's template and descendant component's templates.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-oo7twb?file=src%2Fapp%2Fhello.component.ts

## 🔥 Exception or Error
Notice that all 3 `<p>` elements are styled with the `::after` text. The first one should not get the style.

## 🌍  Your Environment
Angular 7.2.13

**Comment by robwormald** [comment]
As far as I can tell, the style compiler is just stripping out the `::ng-deep` selector and adding it to the document:

Input:
```css
::ng-deep .hello-header {
  background-color: blue;
}
```
Output
```css
.hello-header {
  background-color: blue;
}
```
Whereas it should probably be 
```css
[_nghost-c0] .hello-header {
  background-color: blue;
}
```
