### ISSUE TITLE
StyleUrlResolver strips quotes from inlined SVG styles

### ISSUE THREAD

**Issue by TedSander** [angular/angular#3304]
If the following CSS is added to a component:
```css
.mdl-checkbox__tick-outline{background:rgb(55,71,79) url('data:image/svg+xml;utf8,<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1 1" preserveAspectRatio="xMinYMin meet"> <path d="M 0.04038059,0.6267767 0.14644661,0.52071068 0.42928932,0.80355339 0.3232233,0.90961941 z M 0.21715729,0.80355339 0.85355339,0.16715729 0.95961941,0.2732233 0.3232233,0.90961941 z" id="rect3780" style="fill:#ffffff;fill-opacity:1;stroke:none" /></svg>')}
```

The following css is added to the document:
```css
.mdl-checkbox__tick-outline{background:rgb(55,71,79) url('data:image/svg+xml;utf8,<?xml version=1.0 encoding=UTF-8 standalone=no?><svg xmlns:dc=http://purl.org/dc/elements/1.1/ xmlns:cc=http://creativecommons.org/ns# xmlns:rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# xmlns:svg=http://www.w3.org/2000/svg xmlns=http://www.w3.org/2000/svg version=1.1 viewBox=0 0 1 1 preserveAspectRatio=xMinYMin meet> <path d=M 0.04038059,0.6267767 0.14644661,0.52071068 0.42928932,0.80355339 0.3232233,0.90961941 z M 0.21715729,0.80355339 0.85355339,0.16715729 0.95961941,0.2732233 0.3232233,0.90961941 z id=rect3780 style=fill:#ffffff;fill-opacity:1;stroke:none /></svg>')}
```
Notice that all of the quotes are stripped from the inlined SVG. This causes the SVG to be rendered incorrectly.

I believe the bug is in StyleUrlResolver as when I shortcut the regular expressions the SVGs are rendered correctly.
