### ISSUE TITLE
Angular Build artifacts issue when loading behind spring boot proxy

### ISSUE THREAD

**Issue by devbikshu** [angular/angular#34692]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
 
I came across a weird scenario that I have to load multiple angular application behind proxy so that when user accessing through spring boot gateway it looks like a single page application for end user.

For this i have created 3 angular applications:

accs-m which is the container application running on port 8050 holding navigation bar links.
cp-management sub application running on port 9000
cp-matching sub application running on port 9100
For this we are using Spring Boot Gateway application and inside it we are writing predicates as below Gateway application running on port: http://localhost:8762/accsm

```
- id: cp-management
        uri: http://localhost:9000/cp-create-cp-create-module-ngfactory.js
        predicates:
        - Path=/accsm/cp-create-cp-create-module-ngfactory.js

      - id: cp-matching
        uri: http://localhost:9100/cp-matching-cp-matching-module.js
        predicates:
        - Path=/accsm/cp-matching-cp-matching-module.js

      - id: accs-m
        uri: http://localhost:8050/accsm
        predicates:
        - Path=/accsm/**
```
After this configuration when i am trying to access the applications using gateway with : http://localhost:8762/accsm

It was throwing 404 not found error for build artifacts like (runtime.js, pollyfills.js etc..).

http://localhost:8762/accsm/runtime.js
http://localhost:8762/accsm/vendor.js
http://localhost:8762/accsm/styles.js
http://localhost:8762/accsm/main.js
After my analysis i got to know that when i am sending request from gateway it is looking 'accsm' so i added base herf as

<base href="accsm">  
In my first application which is running on port : http://localhost:8050/ so my issue was resolved and now my first application is serving successfully behind proxy.

Now coming to actual issue : after navigation to any module from navbar when i am doing page refresh all my build artifacts are again showing 404 not found error. Because this time my request has changed as below:

http://localhost:8762/accsm/accsm/runtime.js
http://localhost:8762/accsm/accsm/vendor.js
http://localhost:8762/accsm/accsm/styles.js
http://localhost:8762/accsm/accsm/main.js
I have attached screenshot of my proxy approach for reference.

![micro-frontend](https://user-images.githubusercontent.com/18551819/72057682-c7941080-32f4-11ea-99bd-2322d4aee54e.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
