### ISSUE TITLE
Benchmark generator

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3510]
Create a tool that generates apps given app descriptor. This tool can be used to:

- emulate specific usage patterns, such as:
  - apps with large number of components
  - small apps
  - table-heavy views
  - deep hierarchies
  - multi-apps
- measure application load time (e.g. how long does `bootstrap` function take)
- measure generated code size

## Proposal

Application descriptor is a YAML file. Example:

```yaml
# The top-level component
entrypoint: Shell

# A component: "Shell" is both the name of component class and its element
Shell:
  template:
    - Screen1:
        # nestingLevel indicates how many levels deep a node should appear
        nestingLevel: 3
        # whether the node is guarded by a conditional (e.g. *ng-if)
        branch: if
        # the number of property bindings on this node
        props: 3
    - Screen2:
        nestingLevel: 3
        branch: if
        props: 1

Screen1:
  template:
    # if node name begins with a capital letter, it's a nested component
    - ScreenHeader:
        props: 5
    # if node name begins with a small letter, it's a plain HTML element
    - div:
        # how many times to repeat this node (note this is different from branch/repeat)
        repeat: 20

Screen2:
  template:
    - ScreenHeader:
        props: 5
    - div:
        nestingLevel: 3
        # whether the node is conditionally repeated (e.g. by *ng-for)
        branch:
          repeat: 10

ScreenHeader:
  template:
    - div:
        nestingLevel: 3
        repeat: 3
```
