### ISSUE TITLE
Shadow DOM Emulation

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4088]
Hi all!

I've been working around with shadow dom, but unfortunately only chrome and firefox are currently supporting it. So, in the meantime i've been using the Emulation.
With that said, I have a couple of questions:
<ol>
    <li>Is there an API I can use to manipulate the DOM and Shadow DOM? I only know about ElementRef Class to manipulate the Light DOM (let's call it that way).</li>
    <li>As far as I am concerned, the Shadow DOM Emulation works this way:
        <ol>
            <li>Add an attribute ('ng-host' working with 'ng-content') to each of the existing html tags present on the component's HTML.</li>
            <li>Add the css with attribute to the head HTML tag so it matches the existing html tags with that attribute.</li>
       </ol>
    </li>
    <li>Unfortunately, If one of the existing HTML tag is another component, it will add the attribute only to the component tag, since the adding of the attributes occur during the compiling ( onInit() ? ) of the component with shadow DOM, so the child components are not resolved yet (and their inner HTML does not get the attribute).
Well, that behaviour makes sense since the Shadom DOM is supposed to affect only the current component. But is it possible to change the inner components' CSS?</li>
</ol>

Best regards,
Tiago Braga

**Comment by PascalPrecht** [comment]
If you do use native Shadow DOM, you also need to use dedicated CSS selectors. Angular will rewrite them for you then.

**Comment by TiagoBraga39** [comment]
It should at least...

<b>What I wrote:</b>
```css
.more-options-menu icon-button /deep/ i { 
    width: 50px !important; 
}
```

<b>The output:</b>
```css
.more-options-menu[_ngcontent-ckg-0] icon-button[_ngcontent-ckg-0] i[_ngcontent-ckg-0] {
    width: 50px !important;
}
```

<b>The expected output:</b>
```css
.more-options-menu[_ngcontent-ckg-0] icon-button[_ngcontent-ckg-0] i {
    width: 50px !important;
}
```
