### ISSUE TITLE
Strange flickering with PWA version of angular.io

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#42365]
# Docs or angular.io Bug Report

### Description

 When I start the PWA version of the angular.io, I get a strange CSS glitch at the far left corner of the app.

### What's the affected URL?**
 The landing page of the application

### Reproduction Steps**

Try to open the PWA version in either Windows or Mac

## Screenshot

Windows: 
![angular-io](https://user-images.githubusercontent.com/7170892/119720893-3682f280-be73-11eb-9958-e78d759e2899.gif)

Mac: https://www.loom.com/share/e10a7358628f4c6ea4b64078e4be3041

## Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment]
It seems to me that this is a flash of unstyled content... I have also started seeing this occasionally on the normal website (not just the PWA). We should investigate.

**Comment by bampakoa** [comment]
@petebacondarwin I have uploaded more clues from my findings after the new version of io that went live today. I have also managed to get a screenshot of the exact time that the flash occurs. I hope that helps.

![aio](https://user-images.githubusercontent.com/7170892/119897759-96e46380-bf49-11eb-95a1-277fe4c84d03.gif)
![flickering](https://user-images.githubusercontent.com/7170892/119897781-9ea40800-bf49-11eb-90ee-6848d8c7b84c.png)

**Comment by petebacondarwin** [comment]
Currently we have two hypotheses:

1) Chrome is caching the HTML from a previously rendered page and showing it before the CSS has been processed.
2) The new inline critical styles feature of the CLI makes the CSS stylesheet download non-blocking, which allows the Angular application to bootstrap and start rendering before the CSS has completed its download.

I think 2) is the more likely, since I have only noticed this happening recently, which coincides with the release of the feature on the CLI.

Indeed looking at the page source for angular.io/index.html, we see the following "critical inlined css":

```css
html {
  font-size: 62.5%;
}

body {
  font-family: Roboto, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial,
    Lucida Grande, sans-serif;
  margin: 0;
  font-size: 16px;
  font-size: 1.6rem;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
body,
html {
  height: 100%;
}
@media print {
  * {
    box-shadow: none !important;
  }
  body {
    background: none !important;
  }
}
```

And then the main stylesheet is loaded for `print` media only to make it non-blocking and only enabled (by setting the media value to `all` when it has loaded:

```html
<link rel="stylesheet" href="styles.581eaab3eb8288d25b2c.css" media="print" onload="this.media='all'">
```

I think that until we can ensure that the critical CSS that is extracted is valid for our start up, we should disable the critical inlining on this project.
