### ISSUE TITLE
"ASSERTION ERROR: Malformed style" fails for percent in @keyframes under Ivy consumeWhitespace

### ISSUE THREAD

**Issue by 1-0-1** [angular/angular#42982]
### Which @angular/* package(s) are the source of the bug?

animations, common

### Is this a regression?

Yes

### Description

This looks like a similar issue to #37292.  Issue is happening in core consumeWhitespace since it is limiting to charCodeAt 32 but percent is 37.

### Please provide the exception or error you saw

```true
Error: ASSERTION ERROR: Malformed style at location 2 in string '70[>>%<<]'. Expecting ':'.
    at throwError (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:192328:11)
    at malformedStyleError (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208622:11)
    at consumeSeparator (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208547:13)
    at parseStyleNext (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208472:13)
    at parseStyle (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208447:12)
    at styleStringParser (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208708:18)
    at toStylingKeyValueArray (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:209153:9)
    at checkStylingMap (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208817:119)
    at ɵɵstyleMap (https://*****/vendor-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:208696:5)
    at INTCTableComponent_ng_container_15_ng_container_3_td_1_Template (https://*****/main-es2015.js?v=9bb0f9ff84d3ba7272c8f1d4a06143cb:45224:69)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.14
Node: 14.17.0
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.14
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.8
```

### Anything else?

```css
@-webkit-keyframes tada {
    0% {
        -webkit-transform: scale(1);
        transform: scale(1);
    }

    10%,
    20% {
        -webkit-transform: scale(.9) rotate(-8deg);
        transform: scale(.9) rotate(-8deg);
    }

    30%,
    50%,
    70% {
        -webkit-transform: scale(1.3) rotate(8deg);
        transform: scale(1.3) rotate(8deg);
    }

    40%,
    60% {
        -webkit-transform: scale(1.3) rotate(-8deg);
        transform: scale(1.3) rotate(-8deg);
    }

    80% {
        -webkit-transform: scale(1) rotate(0);
        transform: scale(1) rotate(0);
    }
}

@keyframes tada {
    0% {
        -webkit-transform: scale(1);
        -ms-transform: scale(1);
        transform: scale(1);
    }

    10%,
    20% {
        -webkit-transform: scale(.9) rotate(-8deg);
        -ms-transform: scale(.9) rotate(-8deg);
        transform: scale(.9) rotate(-8deg);
    }

    30%,
    50%,
    70% {
        -webkit-transform: scale(1.3) rotate(8deg);
        -ms-transform: scale(1.3) rotate(8deg);
        transform: scale(1.3) rotate(8deg);
    }

    40%,
    60% {
        -webkit-transform: scale(1.3) rotate(-8deg);
        -ms-transform: scale(1.3) rotate(-8deg);
        transform: scale(1.3) rotate(-8deg);
    }

    80% {
        -webkit-transform: scale(1) rotate(0);
        -ms-transform: scale(1) rotate(0);
        transform: scale(1) rotate(0);
    }
}

.faa-tada.animated,
.faa-tada.animated-hover:hover,
.faa-parent.animated-hover:hover>.faa-tada {
    -webkit-animation: tada 2s linear infinite;
    animation: tada 2s linear infinite;
}
```
