### ISSUE TITLE
Angular 12 + Windows 10 + Docker always polling

### ISSUE THREAD

**Issue by pacocom** [angular/angular#43779]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When I update to latest Angular version and try to use Windows 10 + Docker + Angular, poll execute always every 500 milliseconds instead of after file change in 500 milliseconds, that is, without touching any file, the live reload is executed again every 500 milliseconds.
![image](https://user-images.githubusercontent.com/7735329/136541896-8c6a55a3-6824-4182-ac45-1a9d5b40eed7.png)

package.json
```
  "scripts": {
    "ng": "ng",
    "watch": "ng serve --host 0.0.0.0 --poll 500",
  },
```

Dockerfile
```
FROM node:12.22.6-stretch

# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# you'll likely want the latest npm, regardless of node version, for speed and fixes
RUN npm install npm@"<7" -g

EXPOSE 4200

# install dependencies first
WORKDIR /opt/app/portal/ui
COPY package*.json ./
RUN npm install --no-optional
```
docker-compose.yml
```
version: "3.6"

services:
  portal-ui:
    build:
      context: ui
      args:
        - NODE_ENV=development

    ports:
      - "4200:4200"
      - "49153:49153"

    command: npm run watch

    tty: true # nice logs colors

    volumes:
      - ./ui:/opt/app/portal/ui:delegated
      - nm1:/opt/app/portal/ui/node_modules
```

### Please provide the environment you discovered this bug in

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.8
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.8 (cli-only)
@angular-devkit/core         12.2.8 (cli-only)
@angular-devkit/schematics   12.2.8 (cli-only)
@schematics/angular          12.2.8 (cli-only)
```
