### ISSUE TITLE
View encapsulation breaks with new CSS Layers syntax

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#45389]
[CSS Layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) is a new CSS feature that lets developers organize their CSS into layers, giving better control over specificity. Chrome and Firefox support this feature, and it has now landed in the Safari Technology Preview. 

It appears that Angular's style encapsulation bails out when encountering this new syntax. Style rules declared in a `@layer` declaration are not encapsulated:

```css
/* This will not be encapsulated */
@layer utilities {
  p {
    color: darkgreen;
  }
}

/* This will be encapsulated */
p {
  font-size: 40px;
}
```

Emits:
```html
<style>
  @layer utilities {
    p {
      color: darkgreen;
    }
  }

  p[_ngcontent-mvb-c45] {
    font-size: 40px;
  }
</style>
```

**Reproduction:** https://stackblitz.com/edit/angular-ivy-qce65m?file=src%2Fapp%2Fapp.component.css
