### ISSUE TITLE
Using abstract sass classes does not apply nested styles when added to :host

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#46466]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am trying to extend an abstract class on `:host` selector and it works well until my abstract class has some nested selector styles.
Imagine this:
```scss
%test-hover {
  color: green;
  &:hover {
    color: gray;
  }
}

:host {
  @extend %test-hover;
}
```

It generates this:
```css
[_nghost-dxc-c100] {
  color: green;
}
```
But should generate this:
```css
[_nghost-dxc-c100] {
  color: green;
}
[_nghost-dxc-c100]:hover {
  color: gray;
}
```
However it works fine the nested selector does not have `&`.
```scss
%test-hover {
  color: green;
  :hover {
    color: gray;
  }
}

:host {
  @extend %test-hover;
}
```
Produces this:
```css
[_nghost-gmj-c100] {
  color: green;
}
[_nghost-gmj-c100]   [_ngcontent-gmj-c100]:hover {
  color: gray;
}
```

I believe it should work for `:host` with `&` too.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.3.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, youtube-player

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1303.3
@angular-devkit/build-angular    13.3.3
@angular-devkit/core             13.3.3
@angular-devkit/schematics       13.3.3
@angular-devkit/schematics-cli   13.3.3
@angular/cli                     13.3.3
@schematics/angular              13.3.3
ng-packagr                       13.3.1
rxjs                             7.5.5
typescript                       4.6.3
```

**Comment by JoostK** [comment]
The SASS with `&` is compiled into:

```css
:host {
  color: green;
}
:hover:host {
  color: gray;
}
```

for which I prepared a test case and the CSS shimming logic does generate:

```css
[_nghost-%COMP%] {
  color: green;
}
:hover[_nghost-%COMP%] {
  color: gray;
}
```

so this does not reproduce for me. Can you please share a reproduction?
