### ISSUE TITLE
[scss] `@at-root` is not as expected with `ViewEncapsulation.Emulated`

### ISSUE THREAD

**Issue by JounQin** [angular/angular#48044]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

input:

```scss
p {
  font-family: Lato;
  color: red;

  @at-root html[lang='en'] & {
    color: green;
  }
}
```

output:

```css
p[_ngcontent-qxd-c44] {
  font-family: Lato;
  color: red;
}

html[lang="en"][_ngcontent-qxd-c44] p[_ngcontent-qxd-c44] {
  color: green;
}
```

### Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-7pzzwr?file=src%2Fapp%2Fapp.component.scss

### Exception or Error

```text
The output is expected to be


p[_ngcontent-qxd-c44] {
  font-family: Lato;
  color: red;
}

html[lang="en"] p[_ngcontent-qxd-c44] {
  color: green;
}
```

related angular/angular-cli#9617

### Your Environment

```text
Angular CLI: 11.2.3
Node: 16.18.1
OS: darwin arm64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.2
@angular-devkit/core         11.2.3
@angular-devkit/schematics   11.2.3
@angular/cdk                 11.2.3
@angular/cli                 11.2.3
@angular/flex-layout         11.0.0-beta.33
@schematics/angular          11.2.3
@schematics/update           0.1102.3
rxjs                         6.6.6
```
