### ISSUE TITLE
Keyframe scoping fails in some cases when there are no spaces between multiple animations

### ISSUE THREAD

**Issue by boxmein** [angular/angular#49068]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Keyframe scoping (introduced in 4d6a1d672210219328b33f4f96210870563066ee) adds a regexp-based processor that transforms `@keyframes X` and `animation-name: X` to a prefixed/scoped value to provide emulated keyframe encapsulation.

It seems that a missing space is able to trip the processor up, so it processes the `@keyframes` declaration but not the `animation` declaration. This only happens if your animation shorthand is in the wrong order, i.e. `animation-name` is specified first.

The bug goes away if:

* You don't use `ViewEncapsulation.Emulated`
* You add a space between `,` and `foo` in the below example
* You use the spec compliant order with animation-name last

For example:

```css
@keyframes foo { ... }
@keyframes bar { ... }

#my-div {
    /* prettier-ignore */
    animation: bar 1s infinite,foo 1s infinite; /* THIS BUG: foo is not processed */
    animation: bar 1s infinite, foo 1s infinite; /* OK: foo is processed */
    animation: 1s infinite bar,1s infinite foo; /* OK: foo is processed */
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-eebqcd

### Please provide the exception or error you saw

```true
Some forms of animation shorthand syntax do not correctly process the keyframe scoping issues
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/{compiler, core, ...}: 15.1.2
rxjs: 7.8.0
tslib: 2.5.0
zone.js: 0.12.0
```

### Anything else?

* Angular libraries compiled with older versions minify CSS before distribution to NPM, so you may stumble upon this bug by accidentally using the wrong shorthand order even if your whitespace is correct

**Comment by eTallang** [comment]
I struggled with the same thing. Fixed it by placing the duration before the animation name.

**Comment by puckowski** [comment]
I think PR https://github.com/angular/angular/pull/56800 may resolve this issue. I tested against the Stackblitz listed in this repo (upgraded to next), applied the patch in PR #56800, and the output CSS in main.js is as follows:

```
@keyframes _ngcontent-%COMP%_foo{
  0%{
    color:red
  }
  to{
    color:green
  }
}
@keyframes _ngcontent-%COMP%_bar{
  0%{
    background:green
  }
  to{
    background:red
  }
}
#first[_ngcontent-%COMP%]{
  animation:1s infinite ease _ngcontent-%COMP%_foo,1s infinite ease _ngcontent-%COMP%_bar
}
#second[_ngcontent-%COMP%], #third[_ngcontent-%COMP%]{
  animation:_ngcontent-%COMP%_foo 1s ease infinite,_ngcontent-%COMP%_bar 1s ease infinite
}
```

**Comment by puckowski** [comment]
Double checking my prior testing. I downloaded the StackBlitz listed in issue and upgraded to current Angular next on my local machine.

Current Angular next prod build (without #56800):

```css
<style>
@keyframes _ngcontent-ng-c3888386579_foo{
  0%{
    color:red
  }
  to{
    color:green
  }
}
@keyframes _ngcontent-ng-c3888386579_bar{
  0%{
    background:green
  }
  to{
    background:red
  }
}
#first[_ngcontent-ng-c3888386579]{
  animation:1s infinite ease _ngcontent-ng-c3888386579_foo,1s infinite ease _ngcontent-ng-c3888386579_bar
}
#second[_ngcontent-ng-c3888386579], #third[_ngcontent-ng-c3888386579]{
  animation:_ngcontent-ng-c3888386579_foo 1s ease infinite,bar 1s ease infinite
}
</style>
```

With #56800 manually added on top of current Angular next prod build:

```css
<style>
@keyframes _ngcontent-ng-c3888386579_foo{
  0%{
    color:red
  }
  to{
    color:green
  }
}
@keyframes _ngcontent-ng-c3888386579_bar{
  0%{
    background:green
  }
  to{
    background:red
  }
}
#first[_ngcontent-ng-c3888386579]{
  animation:1s infinite ease _ngcontent-ng-c3888386579_foo,1s infinite ease _ngcontent-ng-c3888386579_bar
}
#second[_ngcontent-ng-c3888386579], #third[_ngcontent-ng-c3888386579]{
  animation:_ngcontent-ng-c3888386579_foo 1s ease infinite,_ngcontent-ng-c3888386579_bar 1s ease infinite
}
</style>
```
