### ISSUE TITLE
host-context() styling applied to host too

### ISSUE THREAD

**Issue by Xriuk** [angular/angular#51954]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When applying some styling through :host-context() like this:
```css
:host-context(.active) {
  color: #f00;
}
```

The generated css becomes:
```css
.active[_nghost-ng-c460829164], .active [_nghost-ng-c460829164] {
  color: #f00;
}
```

Which effectively applies it in case the host component has the given class too

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vr9fny?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
16.0.1
```

**Comment by JoostK** [comment]
This is also the behavior with read Shadow DOM, so this is working as expected.

**Comment by mizok** [comment]
Hello,

I wanted to express my confusion regarding @JoostK JoostK's response. It seems peculiar to me. According to my understanding, when using :host-context(), the expected CSS output should be:

```css
.active [_nghost-ng-c460829164] {
  color: #f00;
}
```
However, the generated CSS provided in the initial post is:


```css
.active[_nghost-ng-c460829164], .active [_nghost-ng-c460829164] {
  color: #f00;
}
```
@JoostK  mentioned that this behavior aligns with the expected behavior when using Shadow DOM. I find this explanation puzzling because, in my understanding, there is no attribute encapsulation when component is using `ViewEncapsulation.ShadowDom`.

Could someone please clarify this or provide additional insights? I appreciate your help in understanding this better.

Thank you

**Comment by mizok** [comment]
I wanted to bring up a concern regarding the compilation behavior of :host-context() in SCSS. When I write SCSS code like the following example:

```scss
:host-context(html.is-mobile) {
  p {
    color: red;
  }
}
```
The generated CSS looks like this:

```scss
html.is-mobile[_nghost-ng-c460829164] p[_nghost-ng-c460829164],
html.is-mobile [_nghost-ng-c460829164] p[_nghost-ng-c460829164] {
  color: red;
}
```
However, the issue here is that html is clearly not a part of the component, yet it's being appended with [_nghost-ng-c460829164]. This behavior is incorrect, as html should not be associated with the component's internal encapsulation identifier.

This seems to be a bug in the compilation process where html is being incorrectly treated as a part of the component. It should not have the [_nghost-ng-c460829164] attribute appended to it. I believe this needs to be addressed to ensure accurate and expected CSS output.

Thank you for your attention to this matter.

Best regards
