### ISSUE TITLE
Add option to disable the transformer in debug mode

### ISSUE THREAD

**Issue by ochafik** [angular/angular#5379]
Since the transformer slows down the build considerably on large codebases, and things just work in dartium with mirrors, would be *great* to have a switch that enables the transformers for `pub build` (`[--mode=release]`) and disable it in `pub serve` (`[--mode=debug]`).

```yaml
transformers:
- angular2:
    releaseOnly: true
```
