### ISSUE TITLE
Use WebGL for testing in continuous integration

### ISSUE THREAD

**Issue by perotom** [angular/angular#57044]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

One essential feature of every framework are automated tests. Some applications use WebGL but sadly it doesn't work with the basic setup (I use Mapbox GL). 

I tried myself the following:

Gitlab CI:
```
test:
  image: node:lts-alpine
  stage: quality
  only:
    - master
  needs: ["install"]
  before_script:
    # Download Chrome
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
    - export CHROME_PATH=/usr/lib/chromium/
    # X Server
    - apk add xvfb
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
```

karma.config:
```
browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    }
```

I tried multiple flags like `–-enable-webgl`, `--disable-gpu`, `--use-angle=swiftshader`, `--use-gl=angle` without success. I always get an exception "Failed to init WebGL". In non-headless mode it works.

### Proposed solution

Enable WebGL by default or add a description on https://angular.dev/guide/testing#testing-in-continuous-integration how to add WebGL support.

### Alternatives considered

Mocking WebGL which is complicated and sometimes not even possible when using external libraries.
