### ISSUE TITLE
[Doc] change `overflow` property value from `visible` to `scroll`

### ISSUE THREAD

**Issue by 321paranoiawhy** [angular/angular#57174]
### Describe the problem that you experienced

content overflowed can not scroll

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular

### Describe what you were looking for in the documentation

Click the `console` tab in [this link](https://angular.dev/tutorials/learn-angular), and the content will overflow, caused by the following css defined in [_xterm.scss](https://github.com/angular/angular/blob/main/adev/src/styles/_xterm.scss#L39-L45):

```css
.xterm-screen {
  padding: 10px;
  box-sizing: border-box;
  overflow: visible !important;
  height: 100% !important;
  width: 100% !important;
}
```

and should be changed to:

```diff css
.xterm-screen {
  padding: 10px;
  box-sizing: border-box;
- overflow: visible !important;
+ overflow: scroll !important;
  height: 100% !important;
  width: 100% !important;
}
```

orelse maybe `oveflow-y: scroll !important;`
