### ISSUE TITLE
CSP in chrome app with angular 2

### ISSUE THREAD

**Issue by Kleak** [angular/angular#5956]
i have rewrite the example given on angular.io and after building the project and launch it as a chrome app i have some trouble with csp...

here is my pubspec.yaml
```yaml
name: angula2_example
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
  chrome: 0.8.0
  dart_to_js_script_rewriter: ^0.1.0

transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- chrome
- $dart2js:
    csp: true
```

my manifest.json :
```json
{
  "name": "Angular2 example",
  "version": "1",

  "manifest_version": 2,
  "minimum_chrome_version": "31",

  "icons": {"128": "dart_icon.png"},

  "app": {
    "background": {
      "scripts": ["background.dart.js"]
    }
  }
}
```

my index.html :
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Angular2 example in chrome app</title>
    <script src="main.dart" type="application/dart"></script>
    <script src="packages/browser/dart.js"></script>
  </head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

my main.dart :
```dart
import 'package:angular2/angular2.dart';
import 'package:angular2/bootstrap.dart';

@Component(selector: 'my-app')
@View(template: '<h1>Angular 2</h1>')
class AppComponent {}

main() {
  bootstrap(AppComponent);
}
```

and my background.dart :
```dart
import "package:chrome/chrome_app.dart" as chrome;

main() {
  chrome.app.runtime.onLaunched.listen((data) {
    chrome.CreateWindowOptions createWindowOptions =
        new chrome.CreateWindowOptions();
    createWindowOptions.id = "_angular2-example";
    createWindowOptions.bounds =
        new chrome.ContentBounds(width: 800, height: 600);
    chrome.app.window.create("index.html", createWindowOptions);
  });
}
```

the error :
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".

Thanks
