### ISSUE TITLE
polyfill-unscoped-rule and it's friends can't use attribute value selectors

### ISSUE THREAD

**Issue by TedSander** [angular/angular#6085]
For example consider rule:
```css
polyfill-unscoped-rule {
    content: 'button[priority="1"] > .content';
    color: rgb($r, $g, $b);
    border: 5px solid red;
  }
```

This selector is valid, but the regex that is used in the shim matches on any quote. See:
https://github.com/angular/angular/blob/e667ad3e6b9cab6c645582634e99c1b1cc4dfcba/modules/angular2/src/compiler/shadow_css.ts#L426

This is also a bug in the webcomponentsjs implementation Notice line: https://github.com/webcomponents/webcomponentsjs/blob/c469b0002fa265416c83d5c8363071705e345a43/src/ShadowCSS/ShadowCSS.js#L561
