### ISSUE TITLE
Can not import directive from other package in dart

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#6544]
I have the following app component:

```dart
import 'package:angular2/angular2.dart';
import 'package:angular2/bootstrap.dart';

import 'package:ng2_autogrow_textarea/ng2_autogrow_textarea.dart';

void main() {
  bootstrap(AppComponent);
}

@Component(
    selector: 'my-app',
    directives: const [AutogrowDirective],
    template: '''
    <textarea [autogrow]
              placeholder="Try typing something..."></textarea>
    ''')
class AppComponent {}
```

The rest of the app is just the same as `stagehand web-angular`.

The problem is, the directive doesn't do anything. If I would include the content of the external package, in my own package, then it works. But if I import from an external package, I get this warning:

```
[Warning from TemplateCompiler on untitled33|lib/app_component.ng_meta.json]:
Could not find Directive/Pipe entry for name: AutogrowDirective
. Please be aware that Dart transformers have limited support for reusable, pre-defined lists of Directives/Pipes (aka "directive/pipe aliases"). See https://goo.gl/d8XPt0 for details.
Build completed successfully
```

**Comment by kegluneq** [comment]
This warning (promoted to an error as of 47a3b4d56ba75f888cbe2ba30fdff141fa03283d) means that the `TemplateCompiler` can't find an annotated `@Directive` (or `@Component`) in any of your imports.

Could you please check:

- That the `angular2` transformer is running on `packge:ng2_autogrow_textarea` (that is, declared in the `transformers` section in its pubspec.yaml)
- That `AutogrowDirective` is visible from `package:ng2_autogrow_textarea/ng2_autogrow_textarea.dart`
- That `AutogrowDirective` is annotated as a `@Directive` or `@Component`

**Comment by kasperpeulen** [comment]
@kegluneq I was not aware that it was needed to add it to the transformer? I thought this was only needed if you didn't want to list the directive in `directives` field from @Component

Is the syntax like this?
```
    platform_directives:
    - 'package:ng2_autogrow_textarea/ng2_autogrow_textarea.dart#AutogrowDirective'
```

If so, it still fails with all 3 conditions met.

**Comment by kegluneq** [comment]
You are correct wrt use of `platform_directives`, but in this case what I mean is that your *other* package must declare that it uses the `angular2` transformer, otherwise `AutogrowDirective` will not have its metadata extracted for use by `app_component.dart`.

For example:
ng2_autogrow_textarea/pubspec.yaml:
```yaml
name: ng2_autogrow_textarea
dependencies:
  angular2: 'any'
transformers:
- angular2
```

main_app/pubspec.yaml:
```yaml
name: main_app
dependencies:
  angular2: 'any'
  ng2_autogrow_textarea: 'any'
transformers:
- angular2:
    entry_points:
        - web/main.dart
```

**Comment by kasperpeulen** [comment]
Okay, I understand @kegluneq 

This is how the pubspec looks
```dart
name: ng2_autogrow_textarea
description: Autogrow textarea directive for Angular 2 Dart.
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/kasperpeulen/autogrow.directive.dart
version: 0.0.1+1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-beta.0'
dev_dependencies:
  angular2_testing: '^2.0.0-beta.0'
  test: '^0.12.6+2'
  grinder: '^0.8.0+1'
  coverage: '^0.7.2'
  dart_style: '^0.2.1'
  browser: '^0.10.0+2'
  git: '^0.4.4+2'
transformers:
- angular2:
    entry_points:
    - example/main.dart
```

And the other pubspec looks like this:
```
name: untitled58
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.1
  browser: ^0.10.0
  ng2_autogrow_textarea: any
transformers:
- angular2:
    entry_points: web/main.dart
```

**Comment by kegluneq** [comment]
Having an `entry_points` value should not cause any problems.

Although ng2_autogrow_textarea v0.0.1+1 [on github](https://github.com/kasperpeulen/ng2_autogrow_textarea.dart) has `transformers` properly specified, v0.0.1+1 [on pub](https://pub.dartlang.org/packages/ng2_autogrow_textarea) does not.

Since pub uses pub.dartlang.org by default, the `transformers` setting is not there.

You can see this by specifying your dependency in `untitled58` as a github dependency (see [docs](https://www.dartlang.org/tools/pub/dependencies.html#git-packages))

```yaml
name: untitled58
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.1
  browser: ^0.10.0
  ng2_autogrow_textarea:
    git: https://github.com/kasperpeulen/ng2_autogrow_textarea.dart.git
transformers:
- angular2:
    entry_points: web/main.dart
```

Run `pub serve` again and there will be no warning.
