### ISSUE TITLE
"Exception: Cannot find reflection information on TestabilityRegistry with" with WebWorker example

### ISSUE THREAD

**Issue by zoechi** [angular/angular#7817]
**Steps to reproduce and a minimal demo of the problem**

```yaml
#pubspec.yaml
name: so36272590_webworker
dependencies:
  angular2: ^2.0.0-beta
  browser: ^0.10.0
dev_dependencies:
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    entry_points:
    - web/main.dart
    mirror_mode: verbose
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
    gen_change_detection_debug_info: true
    platform_directives: 'package:angular2/common.dart#COMMON_DIRECTIVES'
- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <script async src="main.dart" type="application/dart"></script>
    <script async src="packages/browser/dart.js"></script>
  </head>
  <body>
    <hello-world></hello-world>
  </body>
</html>
```

```dart
// main.dart
import 'package:angular2/angular2.dart' show TestabilityRegistry, platform, provide;
import 'package:angular2/platform/worker_render.dart'
    show WORKER_RENDER_PLATFORM, initIsolate;
import "package:angular2/src/core/reflection/reflection.dart";
import "package:angular2/src/core/reflection/reflection_capabilities.dart" show ReflectionCapabilities;

void main() {
  reflector.reflectionCapabilities = new ReflectionCapabilities(); // added
  platform([WORKER_RENDER_PLATFORM])
      .asyncApplication(initIsolate("my_worker.dart"));
}
```

```dart
// my_worker.dart
import 'dart:isolate' show SendPort;
import 'package:angular2/core.dart' show Component, Provider, TestabilityRegistry, platform;
import 'package:angular2/angular2.dart' show reflector;
import 'package:angular2/platform/worker_app.dart'
    show RENDER_SEND_PORT, WORKER_APP_APPLICATION, WORKER_APP_PLATFORM;
import "package:angular2/src/core/reflection/reflection.dart";
import "package:angular2/src/core/reflection/reflection_capabilities.dart" show ReflectionCapabilities;

@Component(
    selector: 'hello-world',
    template: '<h1>Hello {{name}}</h1>'
)
class HelloWorld {
  String name = 'Jane';
}

void main(List<String> args, SendPort replyTo) {
  reflector.reflectionCapabilities = new ReflectionCapabilities();
  platform(
      [WORKER_APP_PLATFORM, new Provider(RENDER_SEND_PORT, useValue: replyTo)])
      .application([WORKER_APP_APPLICATION])
      .bootstrap(HelloWorld);
}
```
_What steps should we try in your demo to see the problem?_
Create an app from the files above and launch it in Dartium.

**Current behavior**
Throws

**Other information**
> Dart VM version: 1.16.0-edge.c2700473c49aecd48cb0ac2a73a37a38dfab979c (Mon Mar 28 18:00:17 2016) on "linux_x64"
> angular2 2.0.0-beta.12
