### ISSUE TITLE
Bug in dart version: Application works in Dartium, but breaks in Chrome with definitely erroneous and confusing error messages.

### ISSUE THREAD

**Issue by vadimtsushko** [angular/angular#8305]
My angular2 dart application currently is not working in Chrome. It works without errors in Dartium though. The application itself is not open sourced but I've extracted minimal portion that causes same errors in Chrome. That project is available at https://github.com/vadimtsushko/ng2_broken

Ng2_broken consists of three components and  works in Dartium (successfully navigates between Home and About components).
I Chrome it breaks with errors: 

```
EXCEPTION: Symbol("AppComponent") implements interfaces but does not declare them: Symbol("AfterContentChecked"), Symbol("AfterContentInit"), Symbol("AfterViewChecked"), Symbol("AfterViewInit"), Symbol("DoCheck"), Symbol("OnChanges"), Symbol("OnDestroy"). See https://goo.gl/b07Kii for more info.
EXCEPTION: Symbol("AppComponent") implements interfaces but does not declare them: Symbol("AfterContentChecked"), Symbol("AfterContentInit"), Symbol("AfterViewChecked"), Symbol("AfterViewInit"), Symbol("DoCheck"), Symbol("OnChanges"), Symbol("OnDestroy"). See https://goo.gl/b07Kii for more info.
STACKTRACE:
Symbol("AppComponent") implements interfaces but does not declare them: Symbol("AfterContentChecked"), Symbol("AfterContentInit"), Symbol("AfterViewChecked"), Symbol("AfterViewInit"), Symbol("DoCheck"), Symbol("OnChanges"), Symbol("OnDestroy"). See https://goo.gl/b07Kii for more info.
    at dart.wrapException (http://localhost:8080/main.dart.js:4239:17)
    at dart._assertDeclaresLifecycleHooks (http://localhost:8080/main.dart.js:118016:17)
    at ReflectionCapabilities.dart.ReflectionCapabilities.interfaces$1 (http://localhost:8080/main.dart.js:118131:11)
    at Reflector.dart.Reflector.interfaces$1 (http://localhost:8080/main.dart.js:34335:46)
    at dart.hasLifecycleHook0 (http://localhost:8080/main.dart.js:29746:50)
    at RuntimeMetadataResolver_getDirectiveMetadata_closure.dart.RuntimeMetadataResolver_getDirectiveMetadata_closure.call$1 (http://localhost:8080/main.dart.js:22104:18)
    at WhereIterator.dart.WhereIterator._f$1 (http://localhost:8080/main.dart.js:40454:24)
    at WhereIterator.dart.WhereIterator.moveNext$0 (http://localhost:8080/main.dart.js:40442:20)
    at dart.List.static.List_List$from.H.computeSignature.E.func (http://localhost:8080/main.dart.js:63740:53)
    at WhereIterable.<anonymous> (http://localhost:8080/main.dart.js:63363:18)

```

I definitely do not implement these methods though

I'm on Windows 8 64bit. Use Dart VM version: 1.16.0 (Tue Apr 26 07:06:15 2016) on "windows_x64"). Angular2 2.0.0-beta.16, though I've tried several combinations of angular2 and dart versions without any change in behavior.

**Comment by vadimtsushko** [comment]
I've found the source of the problem - error in my pubspec file. 

Pubspec in last version of my project looks so:

```
name: instock
description: Minimal angular2 application, failing on the dart2js
version: 0.0.2
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.16
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
      - package:angular2/common.dart#COMMON_DIRECTIVES
    entry_points: web/main.dart,
```

That last comma (left out from some time, when there was some additional entry point) cause all the troubles.
So the fault is mine. I'll probably never make that mistake again.

But in my opinion something is  very wrong with this situation: Project totally work in Dartium without any warnings, and totally breaks in Chrome with most bizarre error messages.
