### ISSUE TITLE
Tour of Heroes Tutorial - Dart Angular 2.0.0 beta 17

### ISSUE THREAD

**Issue by tloeffler** [angular/angular#8911]
I follow this tutorial:
https://angular.io/docs/dart/latest/tutorial/toh-pt1.html

The binding [(ngModel)] does not function. The input element is empty and changing the value doesn't change the h2 content.

The TypeScript tutorial works perfect.

**Comment by ericmdantas** [comment]
@tloeffler, what's the content of your `pubspec.yaml`?

**Comment by tloeffler** [comment]
```
name: tour_of_heroes
description: Tour of Heroes
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```
